name: Transform

on: [push, pull_request]

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
      - run: npm install
      - run: npm start -- -v
      - uses: actions/upload-artifact@v2
        with:
          name: transformed.nt
          path: output/transformed.nt
